### ISSUE TITLE
Feature Request: Nodejs Runtime Support

### ISSUE THREAD

**Issue by misterjoshua** [thundra-io/merloc#1]
This looks like a great project. I see we have Java Runtime Support, but I would love to have support for Nodejs as well. I write a lot of TypeScript and I would definitely use this software.

**Comment by kunalshah** [comment]
IMO, There are more people developing lambdas using node.js than Java. So it'd be nice to have node.js runtime support prioritized.

**Comment by cweekly** [comment]
Yes please!

**Comment by serkan-ozal** [comment]
Hi @misterjoshua, @kunalshah, @jlweston, @gabrielcolson, @icysharp, @serdarkaracay, @cbackas, @cryptopunks2, @fanick1, @adminy, @abeatricecti, @cweekly

We have released MerLoc with Node.js support. I would love to get your feedbacks. 
You can check the repo here for the setup instructions: https://github.com/thundra-io/merloc

**Comment by kunalshah** [comment]
> Hi @misterjoshua, @kunalshah, @jlweston, @gabrielcolson, @icysharp, @serdarkaracay, @cbackas, @cryptopunks2, @fanick1, @adminy, @abeatricecti, @cweekly
> 
> 
> 
> We have released MerLoc with Node.js support. I would love to get your feedbacks. 
> 
> You can check the repo here for the setup instructions: https://github.com/thundra-io/merloc

That's a great news!

**Comment by serkan-ozal** [comment]
Closing the issue as Node.js runtime is supported now.
