### ISSUE TITLE
Feature Request: Python support

### ISSUE THREAD

**Issue by nickls** [thundra-io/merloc#3]
Most ML pipelines are written in Python and this tool would be super helpful for debugging and development.

**Comment by rberger** [comment]
Any chance for a Python version anytime soon?

**Comment by boroskoyo** [comment]
Today we have released a new version of MerLoc that adds support for Python, Node.js, Java, Go, and.NET. You can check our README for more info

**Comment by serkan-ozal** [comment]
Hi @nickls, @rberger, @bvand

We have released MerLoc with Python support. I would love to get your feedbacks. 
You can check the repo here for the setup instructions: https://github.com/thundra-io/merloc

**Comment by serkan-ozal** [comment]
Closing the issue as Python runtime is supported now.
